alloy:
  enabled: false
nodeSelector:
  kubernetes.io/arch: arm64
persistence:
  enabled: true
  size: 10Gi
  storageClassName: nfs
pyroscope:
  extraArgs:
    pyroscopedb.max-block-duration: 30m
  resources:
    limits:
      cpu: 300m
      memory: 768Mi
    requests:
      cpu: 100m
      memory: 256Mi
