nodeSelector:
  kubernetes.io/arch: arm64
persistence:
  enabled: true
  size: 15Gi
  storageClassName: nfs
tempo:
  receivers:
    otlp:
      protocols:
        grpc:
          endpoint: 0.0.0.0:4317
        http:
          endpoint: 0.0.0.0:4318
  resources:
    limits:
      cpu: 300m
      memory: 512Mi
    requests:
      cpu: 100m
      memory: 256Mi
  retention: 8760h
  storage:
    trace:
      backend: local
      block:
        bloom_filter_false_positive: 0.05
      local:
        path: /var/tempo/blocks
      wal:
        path: /var/tempo/wal
